theme: jekyll-theme-slate
title: Sei Devlog
description: Welcome to my Sei Devlog.

# Navigation structure
navigation:
  - title: Home
    url: /
  - title: About
    url: /about/

# Keep this line to show future dated posts (if any of your posts have future dates)
future: true
